# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Templates
email: langnang.chen@outlook.com

baseStorageUrl: https://cdn.jsdelivr.net/gh/langnang/storage
baseFaviconUrl: https://cdn.jsdelivr.net/gh/langnang/storage/img/favicon
baseLogoUrl: https://cdn.jsdelivr.net/gh/langnang/storage/img/logo

storageUrl:
  base: https://cdn.jsdelivr.net/gh/langnang/storage/
  favicon: https://cdn.jsdelivr.net/gh/langnang/storage/img/favicon/
  logo: https://cdn.jsdelivr.net/gh/langnang/storage/img/logo/
  svg: https://cdn.jsdelivr.net/gh/langnang/storage/svg/

siteUrl:
  github: https://github.com/
  gitlab:
  shields: https://img.shields.io/

cdnUrl:
  jsdelivr: https://cdn.jsdelivr.net/npm/
  unpkg: https://unpkg.com/
  cdnjs: https://cdnjs.cloudflare.com/

packageUrl:
  npm: https://npmjs.com/package/
  jsdelivr: https://jsdelivr.com/package/npm/
  unpkg: https://unpkg.com/browse/
  packagist: https://packagist.org/packages/
  rubygems: https://rubygems.org/gems/
  cndjs: https://cdnjs.com/libraries/

badgeUrl:
  shields: https://shields.io/badges/
  fury: https://badge.fury.io/

# description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "/templates" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: langnang
github_username: langnang

# Build settings
theme: jekyll-theme-primer
# remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
  - jekyll-gist
  - jekyll-get-json
  - jekyll-seo-tag
  - jekyll-readme-index
  - jekyll-relative-links
  - github-pages
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# readme_index:
#   enabled: true
#   remove_originals: true
#   with_frontmatter: false
relative_links:
  enabled: true
  collections: true
include:
  - SUMMARY.md
  - README.md

emoji:
  src: "/assets/images/emoji"

jekyll_get_json:
  - data: svgs
    json: "https://cdn.jsdelivr.net/gh/langnang/storage/json/svg.json"
  - data: websites
    json: "https://cdn.jsdelivr.net/gh/langnang/storage/json/websites.json"
