# GitHub Actions Vue Demo
name: Vue App Build and Deploy to GitHub Page # 名称
on:
  push:
    branches:
      - master # master 分支发生push事件时触发
jobs:
  build-and-deploy: # 任务
    runs-on: ubuntu-latest # 运行环境
    steps: # 运行步骤
      - name: Checkout
        uses: actions/checkout@master # 获取源码

      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
