name: 🚀 Deploy dependencies of laravel8-modules on push with FTP

on:
  push:
    branches:
      - master
    paths:
      - "302.laravel8-modules/composer.json"

jobs:
  deploy:
    name: 🎉 Deploy to langnang.byethost9.com
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      # - name: Switch to corresponding directory
      #   run: cd 302.laravel8-modules

      # - name: Install node dependencies
      #   run: yarn install

      # - name: Laravel mix
      #   run: npm run prod

      - name: Install composer dependencies
        run: cd 302.laravel8-modules && composer install

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # ftp server
          server: ftpupload.net
          # ftp username
          username: b9_36151388
          # ftp password
          password: ${{ secrets.ftp_password }}
          # local dir
          local-dir: ./302.laravel8-modules/vendor/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: /htdocs/vendor/
          # File to Exclude
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*/**
            **/node_modules/**
