name: 🚀 Deploy html on push with FTP

on:
  push:
    branches:
      - master
    paths:
      - "html/**"

jobs:
  deploy:
    name: 🎉 Deploy to langnang.byethost14.com
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      # - name: Use Node.js 14.x
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 14.x

      # - name: Install && Build
      #   run: |
      #     cd nodejs/vue2-element-ui
      #     yarn install
      #     npm run build

      # - name: Install composer dependencies
      # run: cd composer/lumen8-modules && composer install

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # ftp server
          server: ftpupload.net
          # ftp username
          username: b32_28202196
          # ftp password
          password: ${{ secrets.ftp_password }}
          # local dir
          local-dir: ./html/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: /htdocs/templates/html/
          # File to Exclude
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*/**
            **/node_modules/**
